language: generic
sudo: required
services:
 - docker
before_install:
 - docker build -t huseyinyavuz/react-test -f ./client/Dockerfile.dev ./client

script:
 - docker run -e CI=true huseyinyavuz/react-test npm test -- --coverage

after_success:
 - docker build -t huseyinyavuz/multi-client ./client
 - docker build -t huseyinyavuz/multi-nginx ./nginx
 - docker build -t huseyinyavuz/multi-server ./server
 - docker build -t huseyinyavuz/multi-worker ./worker
 #Log in 
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
 - docker push huseyinyavuz/multi-client
 - docker push huseyinyavuz/multi-nginx
 - docker push huseyinyavuz/multi-server
 - docker push huseyinyavuz/multi-worker

